queue_rules:
  - name: default
    # speculative_checks: 3
    # batch_size: 2
    conditions:
      - check-success=CI and Semantic Release / main (test)
      - check-success=Pull Request / build (pull_request)
      - check-success=CI and Semantic Release / main (15) (pull_request) 
      - check-success=GitGuardian Security Checks
pull_request_rules:
  - name: update out-of-sync PR
    conditions:
      - base=master
      - -conflict
      - -draft
    actions:
      update:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: close stale pull request
    conditions:
      - base=master
      - -closed
      - updated-at<14 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it is a mistake.
