import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
  buildDocumentationManifest,
  findRepositoryRoot,
  type DocumentationManifest,
  type PublicHook,
} from "./manifest";

export const HOOKS_ZONE_START = "<!--hookslist start-->";
export const HOOKS_ZONE_END = "<!--hookslist end-->";

const prettierCli = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../node_modules/prettier/bin/prettier.cjs"
);

function formatGeneratedFile(filePath: string, content: string): string {
  return execFileSync(
    process.execPath,
    [prettierCli, "--stdin-filepath", filePath],
    {
      encoding: "utf8",
      input: content,
    }
  );
}

function escapeTableCell(value: string): string {
  return value.replaceAll("|", "\\|").replace(/\s+/g, " ").trim();
}

function categoryLabel(category: string): string {
  const labels: Record<string, string> = {
    animation: "Animation & Timing",
    browser: "Browser APIs",
    dev: "Development & Debugging",
    events: "Event Handling",
    experimental: "Experimental Hooks",
    form: "Form & File Handling",
    keyboard: "Keyboard & Input",
    lifecycle: "Lifecycle & Effects",
    mouse: "Mouse & Touch",
    performance: "Performance & Optimization",
    state: "State Management",
    "state-history": "State History & Time Travel",
    temporal: "Temporal Hooks",
    ui: "UI & Layout",
    utilities: "Utilities & Refs",
    viewport: "Window & Viewport",
  };
  return labels[category] ?? category;
}

function hookTable(hooks: PublicHook[]): string {
  return [
    "| Hook | Description | Entrypoint |",
    "| --- | --- | --- |",
    ...hooks.map(
      (hook) =>
        `| [\`${hook.name}\`](https://rooks.vercel.app${hook.route}) | ${escapeTableCell(hook.description)} | \`${hook.entrypoint}\` |`
    ),
  ].join("\n");
}

export function renderHooksZone(manifest: DocumentationManifest): string {
  const byEntrypoint = new Map<string, number>();
  const byCategory = new Map<string, PublicHook[]>();
  for (const hook of manifest.publicHooks) {
    byEntrypoint.set(
      hook.entrypoint,
      (byEntrypoint.get(hook.entrypoint) ?? 0) + 1
    );
    byCategory.set(hook.category, [
      ...(byCategory.get(hook.category) ?? []),
      hook,
    ]);
  }

  const result = [
    "<!-- Generated by `pnpm docs:generate`. Do not edit this zone by hand. -->",
    "",
    `**${manifest.publicHooks.length} canonical hook implementations** are available across three entrypoints. Aliases are listed separately and do not inflate this count.`,
    "",
    "| Entrypoint | Canonical hooks |",
    "| --- | ---: |",
    ...["rooks", "rooks/experimental", "rooks/temporal"].map(
      (entrypoint) =>
        `| \`${entrypoint}\` | ${byEntrypoint.get(entrypoint) ?? 0} |`
    ),
    "",
  ];

  for (const [category, hooks] of [...byCategory.entries()].sort(
    ([left], [right]) => left.localeCompare(right)
  )) {
    result.push(
      "<details>",
      `<summary><strong>${categoryLabel(category)} (${hooks.length})</strong></summary>`,
      "",
      hookTable(
        hooks.sort((left, right) => left.name.localeCompare(right.name))
      ),
      "",
      "</details>",
      ""
    );
  }

  result.push(
    "### Supported aliases",
    "",
    "| Alias | Canonical hook | Entrypoint |",
    "| --- | --- | --- |",
    ...manifest.aliases.map((alias) => {
      const canonical = manifest.byName.get(alias.canonicalName);
      return `| \`${alias.name}\` | [\`${alias.canonicalName}\`](https://rooks.vercel.app${canonical?.route ?? `/docs/hooks/${alias.canonicalName}`}) | \`${alias.entrypoint}\` |`;
    })
  );
  return `${result.join("\n").trim()}\n`;
}

export function replaceGeneratedZone(
  readme: string,
  generated: string
): string {
  const start = readme.indexOf(HOOKS_ZONE_START);
  const end = readme.indexOf(HOOKS_ZONE_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `README must contain ${HOOKS_ZONE_START} followed by ${HOOKS_ZONE_END}`
    );
  }
  const contentStart = start + HOOKS_ZONE_START.length;
  return `${readme.slice(0, contentStart)}\n\n${generated.trim()}\n\n${readme.slice(end)}`;
}

function generatedContributors(rootDir: string): string {
  const configPath = path.join(rootDir, ".all-contributorsrc");
  const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
  return `export const contributorsListData = ${JSON.stringify(config, null, 2)};\n`;
}

interface GeneratedFile {
  content: string;
  path: string;
}

export function getGeneratedFiles(rootDir: string): GeneratedFile[] {
  const manifest = buildDocumentationManifest({ rootDir });
  const readmePath = path.join(rootDir, "packages/rooks/README.md");
  const readme = fs.readFileSync(readmePath, "utf8");
  return [
    {
      path: readmePath,
      content: formatGeneratedFile(
        readmePath,
        replaceGeneratedZone(readme, renderHooksZone(manifest))
      ),
    },
    {
      path: path.join(
        rootDir,
        "apps/website/src/components/contributors-list-data.ts"
      ),
      content: formatGeneratedFile(
        path.join(
          rootDir,
          "apps/website/src/components/contributors-list-data.ts"
        ),
        generatedContributors(rootDir)
      ),
    },
  ];
}

export function generateDocumentation({
  check = false,
  rootDir = findRepositoryRoot(),
}: {
  check?: boolean;
  rootDir?: string;
} = {}): void {
  const stale: string[] = [];
  for (const generated of getGeneratedFiles(rootDir)) {
    const current = fs.existsSync(generated.path)
      ? fs.readFileSync(generated.path, "utf8")
      : "";
    if (current === generated.content) continue;
    if (check) {
      stale.push(path.relative(rootDir, generated.path));
    } else {
      fs.mkdirSync(path.dirname(generated.path), { recursive: true });
      fs.writeFileSync(generated.path, generated.content);
      console.log(`Generated ${path.relative(rootDir, generated.path)}`);
    }
  }
  if (stale.length > 0) {
    throw new Error(
      `Generated documentation is stale:\n${stale.join("\n")}\nRun pnpm docs:generate.`
    );
  }
  if (check) console.log("Generated documentation is up to date.");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    const unexpected = process.argv
      .slice(2)
      .filter((argument) => argument !== "--check");
    if (unexpected.length > 0)
      throw new Error(`Unknown argument(s): ${unexpected.join(" ")}`);
    generateDocumentation({ check: process.argv.includes("--check") });
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
