name: Ref matches branch
description: |
  Checks if the current ref (e.g. a tag) matches the given branch.
  If it does, checkout that branch.
inputs:
  name:
    description: The name of the expected branch
    required: true

outputs:
  result:
    description: 1 or 0

runs:
  using: node12
  main: dist/index.js
